name: Build Custom RustDesk Client

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        default: true
        description: 'Upload artifacts'
  release:
    types: [published]

env:
  RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
  RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
  API_SERVER: ${{ secrets.API_SERVER }}

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          choco install -y nasm yasm
          
      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static
        shell: pwsh
          
      - name: Build
        shell: powershell
        run: |
          $env:VCPKG_ROOT = "${{ github.workspace }}\vcpkg"
          python build.py --portable --hwcodec --flutter
          
      - name: Upload Windows Artifact
        if: ${{ inputs.upload-artifact != false }}
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: |
            flutter/build/windows/x64/runner/Release/rustdesk.exe
            flutter/build/windows/x64/runner/Release/*.dll

  build-macos:
    name: Build macOS Universal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          brew install cmake nasm yasm
          
      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install libvpx libyuv opus aom
          
      - name: Build
        run: |
          export VCPKG_ROOT=${{ github.workspace }}/vcpkg
          python3 build.py --portable --hwcodec --flutter
          
      - name: Upload macOS Artifact
        if: ${{ inputs.upload-artifact != false }}
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-macos
          path: |
            flutter/build/macos/Build/Products/Release/RustDesk.app

  build-linux:
    name: Build Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build pkg-config \
            libgtk-3-dev libxcb-randr0-dev libxdo-dev \
            libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev \
            libasound2-dev libpulse-dev libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev libclang-dev \
            libunwind-dev \
            nasm yasm
            
      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install libvpx libyuv opus aom
          
      - name: Build
        run: |
          export VCPKG_ROOT=${{ github.workspace }}/vcpkg
          python3 build.py --portable --hwcodec --flutter
          
      - name: Upload Linux Artifact
        if: ${{ inputs.upload-artifact != false }}
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-linux-x64
          path: |
            target/release/rustdesk
